### PR TITLE
Preparing styling for the future

### PR DESCRIPTION
**Pull request by MaximilianFlechtner**
Tailwind is clearly better than Bootstrap and, above all, it is lighter. I have also adapted the PHP code a little. In the future I would like to write the PHP code as a kind of api so that a cool Vue application or similar can be chosen as the frontend. Unfortunately, with the move, the possibilities of the appearance customisation have been lost, but I will add them back soon.

### CODE REVIEW

**Comment by MaximilianFlechtner** [comment]
@outdoorbits  I think these are breaking changes, would it be possible to move this to a development branch ?

**Comment by outdoorbits** [comment]
Thank you for your huge contribute! Please let me take some time to understand all that.

**Comment by MaximilianFlechtner** [comment]
@outdoorbits Yes, no problem, as I said, it would be best in a development branch because the changes are not yet 100% production ready.

**Review by outdoorbits — APPROVED** [review]
I have been missing the collapse button on the menue - what's on small displays? See later...

**Comment by MaximilianFlechtner** [comment]
@outdoorbits Ok I will finalize the code in the next few days and optimize the mobile version.

**Comment by outdoorbits** [comment]
Hi, sorry, I just do not understand the advantage yet. Your code looks elegant, of course. But the changes of the web UI do not look very clean to me:
Screenshot_20220120_205545
What I'm missing most, is a collapsible menue for small screens.
Could you tell me, why to change?
e

**Comment by MaximilianFlechtner** [comment]
I will adjust the code to provide the previous functions, it was just a quick draft. And I think the article explains it pretty well, you have more control and have a smaller css file.

https://darkghosthunter.medium.com/should-i-use-bootstrap-or-tailwind-bdb2a5328c0b

**Pull request closed without merging**
