### PR TITLE
WIP: command line interface for backup

### PR DESCRIPTION
**Pull request by gadgetmies**
A suggestion for a command line for the backup script that helps to also document the parameters and their possible values.

I implemented the CLI as a separate script in order not to have to make changes to all the call sites. However, if this style is found valuable and preferable, IMO it would be better to replace the current argument parsing to reduce the risk of breaking changes.

### CODE REVIEW

**Review by outdoorbits — COMMENTED** [review]
Oh, argparse is nice! ;-) And so is your scripts communication.
Unfortunately it didn't work in my tests.
I couldn't figure it out yet because of lack of time.
Two things I found:
1. device-identifier-presets shouldn't be 'None' if not set but just '' (empty).
2. `subprocess.call(["python3", "./backup.py", " ".join(argStrings)])`: I Think you should use `subprocess.call(["python3", "./backup.py"] +list(argStrings))`. 

But `python3 cli.py usb usb` anyway returns
`Traceback (most recent call last):
  File "/var/www/little-backup-box/./backup.py", line 932, in <module>
    SourceName                                          = sys.argv[1]
IndexError: list index out of range`

**Comment by gadgetmies** [comment]
Ah, thanks for these! Updated the commit. Not still sure what are the best practices in Python to do the array concatenation and resolving the script path, but the ones in the newest version of the commit seemed to work at least on my Mac.

**Comment by outdoorbits** [comment]
At soon as I'll find the time I'll test it, thank you.
I like this solution and think about integrating it directly into backup.py. What do you think about this?

**Comment by gadgetmies** [comment]
I agree that once the CLI seems good, it would be nice to integrate it to the backup.py. Will need to get my setup fixed before working on that further to be able to test the functionality.

**Review by outdoorbits — COMMENTED** [review]
This looks good. I would prefer to include cloud storages in choice lists. I did some changes in formatting, added the cloud storages and replaced execution just by an example print. This could be a candidate to replace bachup.py __main__. What's your opinion?

**Review by outdoorbits — COMMENTED** [review]
This is just a demo version. To merge it, we have to replace the print command by the execution command. Then we need to integrate it into backup.py. In the same time we have to edit the related files.

**Comment by outdoorbits** [comment]
Thanks for your contribution! I have added your changes to backup.py and adapted the scripts involved.
I'm looking forward to more ideas and contributions!

**Pull request closed without merging**
